# Generated by Django 5.0.1 on 2024-01-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_authorization_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='05AFB1', max_length=6, verbose_name='инвайт-код'),
        ),
    ]
