# Generated by Django 5.0.1 on 2024-01-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='null', max_length=15, unique=True, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='Q7WBEI', max_length=6, verbose_name='инвайт-код'),
        ),
    ]
